resolver: lts-8.2

packages:
- '.'
- location:
    git: https://github.com/kelecorix/servant-auth.git
    commit: 610624a8f30a8a97568b5d00442058d89535ddde
  subdirs:
    - servant-auth
    - servant-auth-server 

extra-deps:
   - directory-1.2.7.1
   - servant-0.8.1
   - http-api-data-0.2.4
   - aws-0.16

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []
