resolver: lts-8.2

packages:
- '.'
- location:
    git: https://github.com/haskell-servant/servant
    commit: b0dbd79a068d9dec509b12c450297d88047de17c
  subdirs:
    - servant
    - servant-server  
- location:
    git: https://github.com/kelecorix/servant-auth.git
    commit: 610624a8f30a8a97568b5d00442058d89535ddde
  subdirs:
    - servant-auth
    - servant-auth-server
- location:
    git: https://github.com/haskell-servant/servant-multipart
    commit: 582d7ef0e2492c8f8492e2a7f25a9bf0ae2fead8
- location:
    git: https://sigrlami:e3fbc18969f77343c8d64130c341dc6ffaef52c0@github.com/smaccoun/wrapid.git
    commit: 45cdf7efb6b05cbc5a19cb0d8992822fc292f63f
  subdirs:
   - back-end/common
#- ../common/    
    
extra-deps:
   - aws-0.16
   - QuickCheck-2.8.2
   - servant-0.10
   - servant-server-0.10
   - servant-swagger-1.1.2.1
   - wreq-0.5.0.0
   
# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []
