version: '2'
services:
  api:
    command: run
    expose:
      - '3001'
    image: 'sigrlami/wrapid:api'
    links:
      - 'db:dblink'
    external_links:
      - db_1
    ports:
      - '3001:3001'
    privileged: true
  db:
    environment:
      - POSTGRES_PASSWORD=wrapid-squeezit
      - POSTGRES_USER=wrapid
    expose:
      - '5432'
    image: 'postgres:9.5'
    ports:
      - '5432:5432'
  apiupload:
    command: run
    expose:
      - '3006'
    image: 'sigrlami/wrapid:api-upload'
    links:
      - 'db:dblink'
    external_links:
      - db_1
    ports:
      - '3002:3002'
    privileged: true
  app:
    command: run
    expose:
      - '3004'
    image: 'sigrlami/wrapid:app'
    links:
      - 'db:dblink'
      - 'api:api'
    external_links:
      - db_1
    ports:
      - '3004:3004'
    privileged: true
  nginx:
    command: run
    expose:
      - '80'
      - '443'
    image: 'sigrlami/wrapid:nginx'
    links:
      - api
      - apiupload
      - app
      - db
    external_links:
      - api_1
      - db_1
      - apiupload_1
      - app_1
    ports:
      - '443:443'
      - '80:80'
