## we need to keep it separate, since we don't want
## to change 
db:
  environment:
    - POSTGRES_PASSWORD=wrapid-squeezit
    - POSTGRES_USER=wrapid
  expose:
    - '5432'
  image: 'postgres:9.5'
  ports:
    - '35432:5432'
